#!/bin/bash

alias g='git'
alias ga='git add --all'
alias gb='git branch'
alias gc='git commit -m'
alias gcue='git config --global user.email'
alias gcun='git config --global user.name'
alias gch='git checkout'
alias gd='git diff HEAD'
alias gl='git log'
alias gpl='git pull'
alias gpop='git pop'
alias gps='git push'
alias gs='git status'
alias gstash='git stash'
